# Uncomment the next line to define a global platform for your project
platform :macos, '14.0'

target 'myMoti' do
  use_frameworks!

  # Firebase Core is required for using any other Firebase services
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
end
